export class TaskConstants {
  public static CONF_PASE_BOVEDA_TAQUILLA = 'CONF-PA-BT';
  public static MOD_ANUL_PASE_BOVEDA_TAQUILLA = 'MOAN-PA-BT';
  public static CONF_SOLICITUD_PASE_TAQUILLA_BOVEDA = 'CONF-SP-TB';
  public static MOD_ANUL_SOLICITUD_PASE_TAQUILLA_BOVEDA = 'MOAN-SP-TB';
  public static CONF_PASE_TAQUILLA_BOVEDA = 'CONF-PA-TB';
  public static MOD_ANUL_PASE_TAQUILLA_BOVEDA = 'MOAN-PA-TB';
  public static DESPACHO_REMESA_SOLICITADA = 'DES-RM-SOL'; 
  public static CIERRE_TAQUILLA = 'CIERRE-TAQ'; 
};





